### ISSUE TITLE
How to configure to Open notes in Obsidian

### ISSUE THREAD

**Issue by santiyounger** [Garulf/Obsidian-Notes#3]
Hi, I was so happy to see this plugin exists in Flow Launcher

I'd love to get it working for me, but right now when I open it the search works correctly

![image](https://user-images.githubusercontent.com/51902730/158019106-f99c7003-f069-4edd-84b9-21d47c08070f.png)

but upon pressing "ENTER" I'm directed to an empty window of Microsoft Edge (which isn't even my default browser, it's Brave)

I'm sure something must be disconfigured in my side, but can you please help me figure out how to solve this

Thanks a lot!, looking forward to making use of this awesome plugin!

**Comment by Garulf** [comment]
Hi @santiyounger!

That's odd, how did you install your copy of Obsidian notes? 

Obsidian notes should have registered its URI scheme with windows upon install. The scheme would look something like this: `obsidian://`. This tells windows to look for any URLs beginning with that scheme to talk to obsidian. 
If this isn't registered with Windows properly, Windows will just try and open it in your default browser. 

Please try and reinstall Obsidian and see if that fixes your issue.

**Comment by santiyounger** [comment]
That's very strange, I installed Obsidian on my Windows 11 set-up through the regular .exe file from the website, strange that URI is not working

I'll see what I can do, so it's no issue related to this plugin? Thanks!
