### ISSUE TITLE
Flow crashes if Obisidan vault is located in a OneDrive Folder Directory when using this plugin

### ISSUE THREAD

**Issue by Deividas951** [Garulf/Obsidian-Notes#8]
Hello.

Issue is described in the summary.

**Comment by Garulf** [comment]
Hi @Deividas951 

Could you please post your `plugin.log` so I can take a look. I don't use OneDrive personally.

**Comment by Deividas951** [comment]
Tried the newest release, seemed to be not crashing anymore.
Thank you very much :)
